---
language: node_js
node_js:
  - node
  - lts/*
cache:
  yarn: true
  directories:
    - ~/.npm
    - .jest
# before_script:
#   - npm install -g npm@latest
script:
  - yarn install
jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script:
        - yarn install
        - yarn global add expo-cli
        - expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - expo build:android
